//
//  BibleData.swift
//  Bible Chat  ·  "Haven" recreation
//
//  Static content: scripture, journey map, library, chat topics, devotional.
//

import Foundation

enum BibleData {

    // MARK: Verses of the day / paywall
    static let dailyVerse = Verse(
        text: "Jesus Christ is the same yesterday and today and forever",
        reference: "Hebrews 13:8")

    static let paywallVerse = "Psalm 56:3 - When I am afraid, I put my trust in you."

    // MARK: Canonical book list (66 books, KJV chapter counts)
    static let books: [BibleBook] = [
        .init(name: "Genesis", abbreviation: "Gen", chapters: 50, testament: .old),
        .init(name: "Exodus", abbreviation: "Exo", chapters: 40, testament: .old),
        .init(name: "Leviticus", abbreviation: "Lev", chapters: 27, testament: .old),
        .init(name: "Numbers", abbreviation: "Num", chapters: 36, testament: .old),
        .init(name: "Deuteronomy", abbreviation: "Deu", chapters: 34, testament: .old),
        .init(name: "Joshua", abbreviation: "Jos", chapters: 24, testament: .old),
        .init(name: "Judges", abbreviation: "Jdg", chapters: 21, testament: .old),
        .init(name: "Ruth", abbreviation: "Rut", chapters: 4, testament: .old),
        .init(name: "1 Samuel", abbreviation: "1Sa", chapters: 31, testament: .old),
        .init(name: "2 Samuel", abbreviation: "2Sa", chapters: 24, testament: .old),
        .init(name: "1 Kings", abbreviation: "1Ki", chapters: 22, testament: .old),
        .init(name: "2 Kings", abbreviation: "2Ki", chapters: 25, testament: .old),
        .init(name: "1 Chronicles", abbreviation: "1Ch", chapters: 29, testament: .old),
        .init(name: "2 Chronicles", abbreviation: "2Ch", chapters: 36, testament: .old),
        .init(name: "Ezra", abbreviation: "Ezr", chapters: 10, testament: .old),
        .init(name: "Nehemiah", abbreviation: "Neh", chapters: 13, testament: .old),
        .init(name: "Esther", abbreviation: "Est", chapters: 10, testament: .old),
        .init(name: "Job", abbreviation: "Job", chapters: 42, testament: .old),
        .init(name: "Psalms", abbreviation: "Psa", chapters: 150, testament: .old),
        .init(name: "Proverbs", abbreviation: "Pro", chapters: 31, testament: .old),
        .init(name: "Ecclesiastes", abbreviation: "Ecc", chapters: 12, testament: .old),
        .init(name: "Song of Solomon", abbreviation: "Sng", chapters: 8, testament: .old),
        .init(name: "Isaiah", abbreviation: "Isa", chapters: 66, testament: .old),
        .init(name: "Jeremiah", abbreviation: "Jer", chapters: 52, testament: .old),
        .init(name: "Lamentations", abbreviation: "Lam", chapters: 5, testament: .old),
        .init(name: "Ezekiel", abbreviation: "Eze", chapters: 48, testament: .old),
        .init(name: "Daniel", abbreviation: "Dan", chapters: 12, testament: .old),
        .init(name: "Hosea", abbreviation: "Hos", chapters: 14, testament: .old),
        .init(name: "Joel", abbreviation: "Joe", chapters: 3, testament: .old),
        .init(name: "Amos", abbreviation: "Amo", chapters: 9, testament: .old),
        .init(name: "Obadiah", abbreviation: "Oba", chapters: 1, testament: .old),
        .init(name: "Jonah", abbreviation: "Jon", chapters: 4, testament: .old),
        .init(name: "Micah", abbreviation: "Mic", chapters: 7, testament: .old),
        .init(name: "Nahum", abbreviation: "Nah", chapters: 3, testament: .old),
        .init(name: "Habakkuk", abbreviation: "Hab", chapters: 3, testament: .old),
        .init(name: "Zephaniah", abbreviation: "Zep", chapters: 3, testament: .old),
        .init(name: "Haggai", abbreviation: "Hag", chapters: 2, testament: .old),
        .init(name: "Zechariah", abbreviation: "Zec", chapters: 14, testament: .old),
        .init(name: "Malachi", abbreviation: "Mal", chapters: 4, testament: .old),
        .init(name: "Matthew", abbreviation: "Mat", chapters: 28, testament: .new),
        .init(name: "Mark", abbreviation: "Mar", chapters: 16, testament: .new),
        .init(name: "Luke", abbreviation: "Luk", chapters: 24, testament: .new),
        .init(name: "John", abbreviation: "Joh", chapters: 21, testament: .new),
        .init(name: "Acts", abbreviation: "Act", chapters: 28, testament: .new),
        .init(name: "Romans", abbreviation: "Rom", chapters: 16, testament: .new),
        .init(name: "1 Corinthians", abbreviation: "1Co", chapters: 16, testament: .new),
        .init(name: "2 Corinthians", abbreviation: "2Co", chapters: 13, testament: .new),
        .init(name: "Galatians", abbreviation: "Gal", chapters: 6, testament: .new),
        .init(name: "Ephesians", abbreviation: "Eph", chapters: 6, testament: .new),
        .init(name: "Philippians", abbreviation: "Phi", chapters: 4, testament: .new),
        .init(name: "Colossians", abbreviation: "Col", chapters: 4, testament: .new),
        .init(name: "1 Thessalonians", abbreviation: "1Th", chapters: 5, testament: .new),
        .init(name: "2 Thessalonians", abbreviation: "2Th", chapters: 3, testament: .new),
        .init(name: "1 Timothy", abbreviation: "1Ti", chapters: 6, testament: .new),
        .init(name: "2 Timothy", abbreviation: "2Ti", chapters: 4, testament: .new),
        .init(name: "Titus", abbreviation: "Tit", chapters: 3, testament: .new),
        .init(name: "Philemon", abbreviation: "Phm", chapters: 1, testament: .new),
        .init(name: "Hebrews", abbreviation: "Heb", chapters: 13, testament: .new),
        .init(name: "James", abbreviation: "Jas", chapters: 5, testament: .new),
        .init(name: "1 Peter", abbreviation: "1Pe", chapters: 5, testament: .new),
        .init(name: "2 Peter", abbreviation: "2Pe", chapters: 3, testament: .new),
        .init(name: "1 John", abbreviation: "1Jo", chapters: 5, testament: .new),
        .init(name: "2 John", abbreviation: "2Jo", chapters: 1, testament: .new),
        .init(name: "3 John", abbreviation: "3Jo", chapters: 1, testament: .new),
        .init(name: "Jude", abbreviation: "Jud", chapters: 1, testament: .new),
        .init(name: "Revelation", abbreviation: "Rev", chapters: 22, testament: .new),
    ]

    static func book(named name: String) -> BibleBook {
        books.first { $0.name == name } ?? books[0]
    }

    // MARK: Scripture text (KJV) — Genesis 1–3 bundled in full
    static let genesis: [Int: [String]] = [
        1: [
            "In the beginning God created the heaven and the earth.",
            "And the earth was without form, and void; and darkness was upon the face of the deep. And the Spirit of God moved upon the face of the waters.",
            "And God said, Let there be light: and there was light.",
            "And God saw the light, that it was good: and God divided the light from the darkness.",
            "And God called the light Day, and the darkness he called Night. And the evening and the morning were the first day.",
            "And God said, Let there be a firmament in the midst of the waters, and let it divide the waters from the waters.",
            "And God made the firmament, and divided the waters which were under the firmament from the waters which were above the firmament: and it was so.",
            "And God called the firmament Heaven. And the evening and the morning were the second day.",
            "And God said, Let the waters under the heaven be gathered together unto one place, and let the dry land appear: and it was so.",
            "And God called the dry land Earth; and the gathering together of the waters called he Seas: and God saw that it was good.",
            "And God said, Let the earth bring forth grass, the herb yielding seed, and the fruit tree yielding fruit after his kind, whose seed is in itself, upon the earth: and it was so.",
            "And the earth brought forth grass, and herb yielding seed after his kind, and the tree yielding fruit, whose seed was in itself, after his kind: and God saw that it was good.",
            "And the evening and the morning were the third day.",
            "And God said, Let there be lights in the firmament of the heaven to divide the day from the night; and let them be for signs, and for seasons, and for days, and years:",
            "And let them be for lights in the firmament of the heaven to give light upon the earth: and it was so.",
            "And God made two great lights; the greater light to rule the day, and the lesser light to rule the night: he made the stars also.",
            "And God set them in the firmament of the heaven to give light upon the earth,",
            "And to rule over the day and over the night, and to divide the light from the darkness: and God saw that it was good.",
            "And the evening and the morning were the fourth day.",
            "And God said, Let the waters bring forth abundantly the moving creature that hath life, and fowl that may fly above the earth in the open firmament of heaven.",
            "And God created great whales, and every living creature that moveth, which the waters brought forth abundantly, after their kind, and every winged fowl after his kind: and God saw that it was good.",
            "And God blessed them, saying, Be fruitful, and multiply, and fill the waters in the seas, and let fowl multiply in the earth.",
            "And the evening and the morning were the fifth day.",
            "And God said, Let the earth bring forth the living creature after his kind, cattle, and creeping thing, and beast of the earth after his kind: and it was so.",
            "And God made the beast of the earth after his kind, and cattle after their kind, and every thing that creepeth upon the earth after his kind: and God saw that it was good.",
            "And God said, Let us make man in our image, after our likeness: and let them have dominion over the fish of the sea, and over the fowl of the air, and over the cattle, and over all the earth, and over every creeping thing that creepeth upon the earth.",
            "So God created man in his own image, in the image of God created he him; male and female created he them.",
            "And God blessed them, and God said unto them, Be fruitful, and multiply, and replenish the earth, and subdue it: and have dominion over the fish of the sea, and over the fowl of the air, and over every living thing that moveth upon the earth.",
            "And God said, Behold, I have given you every herb bearing seed, which is upon the face of all the earth, and every tree, in the which is the fruit of a tree yielding seed; to you it shall be for meat.",
            "And to every beast of the earth, and to every fowl of the air, and to every thing that creepeth upon the earth, wherein there is life, I have given every green herb for meat: and it was so.",
            "And God saw every thing that he had made, and, behold, it was very good. And the evening and the morning were the sixth day.",
        ],
        2: [
            "Thus the heavens and the earth were finished, and all the host of them.",
            "And on the seventh day God ended his work which he had made; and he rested on the seventh day from all his work which he had made.",
            "And God blessed the seventh day, and sanctified it: because that in it he had rested from all his work which God created and made.",
            "These are the generations of the heavens and of the earth when they were created, in the day that the LORD God made the earth and the heavens,",
            "And every plant of the field before it was in the earth, and every herb of the field before it grew: for the LORD God had not caused it to rain upon the earth, and there was not a man to till the ground.",
            "But there went up a mist from the earth, and watered the whole face of the ground.",
            "And the LORD God formed man of the dust of the ground, and breathed into his nostrils the breath of life; and man became a living soul.",
            "And the LORD God planted a garden eastward in Eden; and there he put the man whom he had formed.",
            "And out of the ground made the LORD God to grow every tree that is pleasant to the sight, and good for food; the tree of life also in the midst of the garden, and the tree of knowledge of good and evil.",
            "And a river went out of Eden to water the garden; and from thence it was parted, and became into four heads.",
        ],
        3: [
            "Now the serpent was more subtil than any beast of the field which the LORD God had made. And he said unto the woman, Yea, hath God said, Ye shall not eat of every tree of the garden?",
            "And the woman said unto the serpent, We may eat of the fruit of the trees of the garden:",
            "But of the fruit of the tree which is in the midst of the garden, God hath said, Ye shall not eat of it, neither shall ye touch it, lest ye die.",
            "And the serpent said unto the woman, Ye shall not surely die:",
            "For God doth know that in the day ye eat thereof, then your eyes shall be opened, and ye shall be as gods, knowing good and evil.",
        ],
    ]

    /// Verses for any book/chapter (Genesis 1–3 real; graceful placeholder otherwise).
    static func verses(book: String, chapter: Int) -> [String] {
        if book == "Genesis", let v = genesis[chapter] { return v }
        return [
            "The reading for \(book) \(chapter) is part of your \(Brand.appName) journey.",
            "Be still, and know that this word is being prepared for you.",
            "Take a breath, and let the quiet ready your heart to receive it.",
            "Every chapter is a doorway; you are always welcome to return.",
        ]
    }

    // MARK: Journey map (streak → postcards)
    static let journeyStops: [JourneyStop] = [
        .init(name: "The Beginning", verse: "In the beginning God created the heaven and the earth.",
              reference: "Genesis 1:1", artwork: .dawn, streaksRequired: 0),
        .init(name: "Garden of Eden", verse: "The Lord God planted a garden eastward in Eden, and there He put the man whom He had formed.",
              reference: "Genesis 2:8", artwork: .garden, streaksRequired: 1),
        .init(name: "Mount Ararat", verse: "And the ark rested in the seventh month, upon the mountains of Ararat.",
              reference: "Genesis 8:4", artwork: .mountains, streaksRequired: 3),
        .init(name: "Bethel", verse: "And he dreamed, and behold a ladder set up on the earth, and the top of it reached to heaven.",
              reference: "Genesis 28:12", artwork: .sunset, streaksRequired: 6),
        .init(name: "Mount Sinai", verse: "And Mount Sinai was altogether on a smoke, because the Lord descended upon it in fire.",
              reference: "Exodus 19:18", artwork: .harvest, streaksRequired: 10),
    ]

    // MARK: Listen library
    static let creationStory = Story(
        title: "Creation: In the Beginning",
        reference: "Genesis 1:1",
        artwork: .darkCreation,
        durationSeconds: 20,
        narration: [
            "The very first sentence of the Bible is also one of its boldest.",
            "No argument, no proof, no build-up — just a statement that reframes everything.",
            "Listen to Genesis chapter one, verse one:",
            "\"In the beginning God created the heavens and the earth.\"",
            "Ten words. And already the Bible has told you who is in charge, when the story starts, and where it's all heading.",
            "But the next verse takes a strange turn:",
            "\"Now the earth was formless and empty.\"",
        ])

    private static func story(_ t: String, _ r: String, _ a: HavenArtwork,
                               _ narration: [String]) -> Story {
        Story(title: t, reference: r, artwork: a,
              durationSeconds: Self.audioDurations[t] ?? max(60, narration.joined(separator: " ").count / 14),
              narration: narration)
    }

    /// Real durations of the bundled narration files (seconds), measured at generation time.
    private static let audioDurations: [String: Int] = [
        "Abraham, Isaac, and Rebekah": 42,
        "Adam and Eve: The Garden Story": 40,
        "By Faith, Abraham": 45,
        "Cain and Abel": 38,
        "Creation: In the Beginning": 20,
        "Crossing the Red Sea": 46,
        "Daniel in the Lion's Den": 45,
        "David and Goliath": 42,
        "Esther, for Such a Time": 44,
        "Jacob and Esau: A Tale of Two Brothers": 42,
        "Jacob's Ladder": 38,
        "Joseph and His Coat of Many Colors": 46,
        "Moses, the Prince of Egypt": 40,
        "Noah and the Ark: Hidden in Plain Sight": 39,
        "Noah and the Flood": 39,
        "On Being Still": 38,
        "Ruth and Naomi": 42,
        "The 10 Commandments: Their Real Purpose": 40,
        "The Adversary": 42,
        "The Passover: Exodus 12": 44,
        "The Vine and the Branches": 42,
    ]

    static let libraryCollections: [LibraryCollection] = [
        .init(title: "Bible Stories", artwork: .river, sections: [
            .init(title: "Creation", subtitle: "The beginning of all things and early humanity", stories: [
                creationStory,
                story("Adam and Eve: The Garden Story", "Genesis 2", .garden, [
            "Before there were cities, before there were nations, there was a garden.",
            "Genesis chapter two slows the camera down and looks closely at the first man and woman.",
            "God forms Adam from the dust of the ground and breathes into him the breath of life.",
            "Dust and breath. Ordinary earth, carrying the very life of God.",
            "Then God says something surprising: \"It is not good for the man to be alone.\"",
            "In a world called good again and again, this is the first thing called not good.",
            "So God makes a helper suitable for him — Eve, drawn from Adam's own side.",
            "Not from his head to rule over him, not from his feet to be walked on, but from his side, to stand beside him.",
            "And the chapter ends with the two of them naked and unashamed.",
            "Fully known, fully seen, and completely unafraid.",
            "That is the picture the whole Bible is trying to get back to.",
            "Rest here for a moment: you were made for that kind of knowing, and that kind of peace.",
        ]),
                story("The Adversary", "Genesis 3", .darkCreation, [
            "Genesis chapter three opens with a question — the first question in the Bible.",
            "\"Did God really say?\"",
            "The serpent is described as more crafty than any of the wild animals God had made.",
            "Notice what the adversary attacks first. Not God's power. Not God's existence. God's word, and God's goodness.",
            "\"You will not certainly die,\" he tells the woman. \"God knows your eyes will be opened, and you will be like God.\"",
            "The lie underneath every other lie: God is holding out on you.",
            "Eve saw that the fruit was good, pleasing, and desirable. She took it, and ate. Adam, who was with her, ate too.",
            "And their eyes were opened — but not the way the serpent promised.",
            "They knew they were naked. They hid.",
            "Yet even here, grace gets the last word.",
            "God comes walking in the garden, calling, \"Where are you?\"",
            "Not because He doesn't know — but because He wants them to come out of hiding.",
            "He is still asking that question today. And He still clothes the ones He finds.",
        ]),
                story("Cain and Abel", "Genesis 4", .harvest, [
            "The first family in the Bible gives us the first brothers — and the first tragedy.",
            "Cain works the soil. Abel keeps flocks. Both bring offerings to the Lord.",
            "God looks with favor on Abel's offering, but not on Cain's.",
            "And Cain's face falls.",
            "Watch what God does next. He doesn't reject Cain. He warns him, gently, like a father.",
            "\"Sin is crouching at your door. It desires to have you, but you must rule over it.\"",
            "Sin, pictured as a wild animal, waiting at the threshold.",
            "Cain doesn't rule over it. He invites his brother into a field, and he rises against him.",
            "Then comes the question that echoes through history: \"Where is your brother?\"",
            "\"Am I my brother's keeper?\" Cain answers.",
            "The rest of Scripture answers back: yes. You are.",
            "Even then, God marks Cain — not to condemn him, but to protect him.",
            "Mercy, even for a murderer. That is the God of Genesis four.",
        ]),
                story("Noah and the Flood", "Genesis 6", .mountains, [
            "By Genesis six, the world God called very good has come undone.",
            "\"The Lord saw how great the wickedness of the human race had become.\"",
            "And the Bible says something staggering: the Lord regretted that he had made human beings, and his heart was deeply troubled.",
            "A grieving God. Not a distant judge — a heartbroken maker.",
            "But Noah found favor in the eyes of the Lord.",
            "One man, walking faithfully with God in a world that had forgotten Him.",
            "God tells Noah to build an ark — a floating sanctuary, measured out in cubits of obedience.",
            "Noah did everything just as God commanded him.",
            "For forty days the rain fell, and the waters rose, and everything on dry land was swept away.",
            "But God remembered Noah. That is the hinge of the whole story.",
            "The wind blows, the waters recede, and a dove returns with a fresh olive leaf.",
            "Judgment is real. But it is never the last word. Remembering is.",
        ]),
                story("Noah and the Ark: Hidden in Plain Sight", "Genesis 7", .river, [
            "Read the flood story slowly and you'll find details hidden in plain sight.",
            "God doesn't just send Noah into the ark. Genesis seven says, \"Then the Lord shut him in.\"",
            "God Himself closes the door.",
            "The safety of Noah does not depend on Noah's grip. It depends on God's hand.",
            "Count the animals again, too: not just two by two — seven pairs of every clean animal.",
            "Provision for worship and sacrifice was loaded on board before the first drop of rain.",
            "God was already planning the altar on the other side of the storm.",
            "And notice the timing the text lingers on — exact days, exact months.",
            "The flood is not chaos to God. Even judgment runs on His calendar.",
            "Whatever storm you are riding out right now, the same details hold.",
            "The door is shut by a faithful hand. Provision is already on board.",
            "And there is a date, known to God, when the waters will recede.",
        ]),
            ]),
            .init(title: "Patriarchs", subtitle: "Stories of Abraham, Isaac, Jacob, and Joseph", stories: [
                story("Jacob's Ladder", "Genesis 28", .sunset, [
            "Jacob is running for his life when heaven opens above him.",
            "He has cheated his brother, deceived his father, and fled with nothing but a staff.",
            "At sunset he stops in the middle of nowhere and puts a stone under his head.",
            "And there, in a dream, he sees a stairway resting on the earth, with its top reaching to heaven.",
            "Angels of God are ascending and descending on it.",
            "Above it stands the Lord, who speaks not one word of rebuke.",
            "Instead: \"I am with you and will watch over you wherever you go.\"",
            "A promise, given to a fugitive, on the worst night of his life.",
            "Jacob wakes and whispers, \"Surely the Lord is in this place, and I was not aware of it.\"",
            "He names the place Bethel — the house of God.",
            "Here is the wonder of this story: the ladder is not something we climb.",
            "Heaven comes down to meet runaways in the dark.",
            "Wherever you are sleeping tonight, the Lord is in that place too.",
        ]),
                story("Joseph and His Coat of Many Colors", "Genesis 37", .goldenField, [
            "Genesis thirty-seven begins with a gift that starts a war.",
            "Jacob loves Joseph more than any of his other sons, and he makes him an ornate robe.",
            "Every time Joseph wears it, his brothers see their father's preference stitched in color.",
            "They hated him, the text says, and could not speak a kind word to him.",
            "Then come the dreams — sheaves bowing, stars bowing — and the hatred hardens into a plan.",
            "They strip the robe, throw Joseph into a cistern, and sell him for twenty shekels of silver.",
            "Then they dip the beautiful coat in goat's blood and let their father draw his own conclusions.",
            "It looks like the end of the story. It is only the beginning.",
            "Because the God of Joseph specializes in writing long stories.",
            "Every betrayal in this chapter is quietly moving Joseph toward Egypt, toward Pharaoh, toward the saving of many lives.",
            "Years later Joseph will say to these same brothers: \"You intended to harm me, but God intended it for good.\"",
            "If you are in the cistern part of your story, keep reading. God is not finished.",
        ]),
                story("Abraham, Isaac, and Rebekah", "Genesis 24", .village, [
            "Genesis twenty-four is the longest chapter in Genesis, and it is a love story.",
            "Abraham is old, Sarah has died, and Isaac — the son of promise — needs a wife.",
            "So Abraham sends his most trusted servant back to his homeland, with camels, gifts, and a mission.",
            "The servant does something remarkable when he arrives: he prays.",
            "\"Lord, give me success today, and show kindness to my master Abraham.\"",
            "He asks for a specific sign — a young woman who will offer water not just to him, but to his camels too.",
            "Before he has finished praying, Rebekah comes out with her jar on her shoulder.",
            "She offers him a drink, then waters all ten camels — gallons and gallons, drawn by hand, unasked.",
            "Kindness beyond what was required. That is the sign.",
            "The servant bows and worships: \"The Lord has led me on the journey.\"",
            "Led. Not pushed, not dragged. Led, step by step, to exactly the right person.",
            "The same God still guides servants who pray on the road.",
        ]),
                story("Jacob and Esau: A Tale of Two Brothers", "Genesis 27", .harvest, [
            "Twins wrestle in Rebekah's womb, and they never really stop.",
            "Esau is born first, red and hairy, a man of the open country.",
            "Jacob comes out grasping his brother's heel — and grasping becomes the story of his life.",
            "One evening Esau comes in famished, and Jacob is cooking stew.",
            "\"First,\" Jacob says, \"sell me your birthright.\"",
            "Esau swears it away for a single meal. The text is blunt: \"So Esau despised his birthright.\"",
            "Years later, with his mother's help, Jacob dresses in Esau's clothes and steals the blessing from blind old Isaac.",
            "Deceit in one generation plants weeping in the next. Esau cries out with a loud and bitter cry.",
            "And yet — God does not abandon this fractured family.",
            "Decades later, the brothers meet again, and Esau runs to Jacob, embraces him, and weeps.",
            "Jacob says, \"To see your face is like seeing the face of God.\"",
            "Grace can reach even the oldest wound in the family.",
            "It is never too late for brothers to run toward each other.",
        ]),
            ]),
            .init(title: "Exodus", subtitle: "Israel's deliverance from Egypt", stories: [
                story("Moses, the Prince of Egypt", "Exodus 2", .sunset, [
            "Exodus chapter two opens under a death sentence.",
            "Pharaoh has ordered every Hebrew baby boy thrown into the Nile.",
            "But one mother looks at her son and sees that he is a fine child, and she hides him three months.",
            "When she can hide him no longer, she obeys Pharaoh with holy irony — she puts her boy in the Nile.",
            "But first she coats a papyrus basket with tar and pitch.",
            "The Hebrew word for that basket is the same word used for Noah's ark.",
            "A tiny ark, riding the river of death, carrying a deliverer.",
            "Pharaoh's own daughter draws him out of the water and names him Moses.",
            "And in God's perfect humor, Moses' mother is hired — and paid — to nurse her own son.",
            "The princess raises in the palace the very child who will bring the empire to its knees.",
            "No decree of any king can drown what God has decided to save.",
            "Whatever river you have been forced to place your treasure upon, God is already downstream.",
        ]),
                story("The Passover: Exodus 12", "Exodus 12", .darkCreation, [
            "Exodus twelve is the night Israel never forgot.",
            "Nine plagues have shaken Egypt, and one final judgment is coming at midnight.",
            "But first, God gives His people something strange: instructions for a meal.",
            "Each household is to take a lamb — a year old, without defect — and care for it four days.",
            "Then, at twilight, the lamb is slain, and its blood is brushed on the doorframes.",
            "\"When I see the blood,\" God says, \"I will pass over you.\"",
            "Not when I see your goodness. Not when I see your effort. When I see the blood.",
            "Inside, they eat with cloaks tucked in and sandals on — dressed for a journey they can hardly imagine.",
            "By morning, Israel is free — four hundred and thirty years of slavery ended in a single night.",
            "God tells them to keep this feast forever, so children will ask, \"What does this ceremony mean?\"",
            "Fifteen centuries later, John the Baptist points at a man from Nazareth:",
            "\"Look, the Lamb of God, who takes away the sin of the world.\"",
            "The doorframe was always pointing to a cross.",
        ]),
                story("Crossing the Red Sea", "Exodus 14", .river, [
            "Freedom lasts about three days before it looks like a terrible mistake.",
            "Israel is camped by the sea when they look up and see Pharaoh's army — six hundred of his best chariots.",
            "Water ahead. Death behind. Nowhere to run.",
            "They cry out to Moses, \"Was it because there were no graves in Egypt that you brought us to the desert to die?\"",
            "Moses answers with some of the most quoted words in Scripture:",
            "\"Do not be afraid. Stand firm, and you will see the deliverance the Lord will bring you today.\"",
            "\"The Lord will fight for you; you need only to be still.\"",
            "Then God says something unexpected: \"Why are you crying out to me? Tell the Israelites to move on.\"",
            "Faith stands still, and then faith moves forward.",
            "Moses stretches his hand over the sea, and all night the Lord drives it back with a strong east wind.",
            "The people walk through on dry ground, with walls of water on their right and on their left.",
            "The same waters that saved Israel swallowed the army that chased them.",
            "There is a path through your sea. It opens when you move toward it.",
        ]),
                story("The 10 Commandments: Their Real Purpose", "Exodus 20", .mountains, [
            "Before God gives Israel a single command, He reminds them of what He has already done.",
            "\"I am the Lord your God, who brought you out of Egypt, out of the land of slavery.\"",
            "Grace comes first. The rescue happens before the rules.",
            "Israel is not saved by keeping the commandments — they receive the commandments because they have been saved.",
            "Read them again with that order in mind.",
            "No other gods. No idols. No misusing His name — because you now carry it.",
            "A Sabbath, because slaves never get a day off, and you are slaves no longer.",
            "Honor your parents. Do not murder. Do not commit adultery. Do not steal. Do not lie. Do not covet.",
            "Four commands about loving God. Six about loving people. Jesus would later fold them into two.",
            "The commandments are not a ladder to climb into God's favor.",
            "They are a description of what freedom looks like when it stays free.",
            "The law is what love does when it has been rescued.",
        ]),
            ]),
        ]),
        .init(title: "Stories for Men", artwork: .mountains, sections: [
            .init(title: "Courage", subtitle: "Men of conviction", stories: [
                story("David and Goliath", "1 Samuel 17", .harvest, [
            "For forty days, a nine-foot champion has stepped out of the Philistine camp and roared the same challenge.",
            "And for forty days, the army of the living God has done nothing but tremble.",
            "Then a shepherd boy arrives with bread and cheese for his brothers.",
            "David hears the taunt once — once — and asks, \"Who is this uncircumcised Philistine that he should defy the armies of the living God?\"",
            "Everyone else measured Goliath against themselves. David measured him against God.",
            "Saul offers his own armor, but David can't even walk in it.",
            "He goes down to the stream and chooses five smooth stones.",
            "Goliath sees a boy and is insulted. David sees a battle that already belongs to the Lord.",
            "\"You come against me with sword and spear and javelin, but I come against you in the name of the Lord Almighty.\"",
            "One stone, one swing, and the giant falls face down.",
            "The story is not that a small man beat a big one.",
            "It is that faith sees what fear cannot: the battle is the Lord's.",
        ]),
                story("Daniel in the Lion's Den", "Daniel 6", .darkCreation, [
            "Daniel is not a young man in the lions' den. He is over eighty.",
            "A lifetime of faithfulness has carried him from exiled teenager to the highest office in a foreign empire.",
            "His rivals cannot find one flaw in him, so they weaponize the only thing left: his prayer life.",
            "A new law: pray to anyone but the king for thirty days, and the lions are waiting.",
            "Daniel hears about the decree — and goes home to pray, three times a day, windows open toward Jerusalem.",
            "Just as he had done before.",
            "No hiding, no pause, no protest. Just the same faithful rhythm that had held him for sixty years.",
            "Even the pagan king spends a sleepless night hoping Daniel's God is real.",
            "At dawn he runs to the den and calls out, \"Has your God been able to rescue you?\"",
            "And a calm voice rises from among the lions: \"My God sent his angel, and he shut the mouths of the lions.\"",
            "The habits you build in ordinary days are what hold you in the den.",
            "Keep the window open. Keep the rhythm. The God of Daniel does not sleep.",
        ]),
            ]),
        ]),
        .init(title: "Stories for Women", artwork: .waterlilies, sections: [
            .init(title: "Faithfulness", subtitle: "Women of strength", stories: [
                story("Ruth and Naomi", "Ruth 1", .goldenField, [
            "The book of Ruth begins with three funerals in five verses.",
            "Naomi has lost her husband and both her sons in a foreign land.",
            "She decides to walk back to Bethlehem, and she tells her widowed daughters-in-law to go home.",
            "One kisses her goodbye. The other clings to her.",
            "Ruth's words have been read at weddings for centuries, but they were first spoken to a grieving mother-in-law:",
            "\"Where you go I will go, and where you stay I will stay.\"",
            "\"Your people will be my people and your God my God.\"",
            "A Moabite widow binds herself to a bitter old woman and to a God she barely knows.",
            "And through that stubborn, everyday loyalty, God quietly rebuilds two shattered lives.",
            "Ruth gleans in the field of a man named Boaz — the right field, on the right day, by no accident.",
            "By the last chapter, Naomi's empty arms hold a grandson.",
            "His name is Obed, father of Jesse, father of David.",
            "Small faithfulness, it turns out, can carry a royal line.",
            "Love that stays is never wasted.",
        ]),
                story("Esther, for Such a Time", "Esther 4", .sunset, [
            "The book of Esther never mentions God's name. Not once.",
            "And that is exactly the point.",
            "A Jewish orphan girl becomes queen of Persia through a sequence of events no one could script.",
            "Then a decree goes out: on a single day, every Jew in the empire is to be destroyed.",
            "Esther's uncle Mordecai sends her a message that has steadied trembling hearts ever since:",
            "\"If you remain silent at this time, relief and deliverance for the Jews will arise from another place.\"",
            "\"And who knows but that you have come to your royal position for such a time as this?\"",
            "Esther answers with fasting and courage: \"I will go to the king, even though it is against the law.\"",
            "\"And if I perish, I perish.\"",
            "She walks into the throne room uninvited — and the scepter extends.",
            "The story turns on banquets, sleepless nights, and impeccable timing.",
            "God's name is absent, but His fingerprints are on every page.",
            "You may not see Him named in your circumstances either. Look for the fingerprints.",
            "You are where you are for such a time as this.",
        ]),
            ]),
        ]),
        .init(title: "By Faith", artwork: .sunset, sections: [
            .init(title: "Hebrews 11", subtitle: "The great cloud of witnesses", stories: [
                story("By Faith, Abraham", "Hebrews 11", .dawn, [
            "Hebrews eleven is often called faith's hall of fame, and Abraham gets the longest tribute.",
            "\"By faith Abraham, when called to go to a place he would later receive as his inheritance, obeyed and went —\"",
            "\"— even though he did not know where he was going.\"",
            "Sit with that phrase. He did not know where he was going.",
            "Faith is not a map. It is a Person you follow without one.",
            "By faith he made his home in the promised land like a stranger, living in tents.",
            "For he was looking forward to the city with foundations, whose architect and builder is God.",
            "By faith Abraham, even though he was past age — and Sarah herself was barren — received power to become a father.",
            "He considered Him faithful who had made the promise.",
            "That is the whole engine of faith: not the size of your believing, but the faithfulness of the One believed.",
            "These all died still living by faith, the chapter says, seeing the promises from a distance and welcoming them.",
            "You can walk without a map today.",
            "The Architect has the blueprints, and He knows the way home.",
        ]),
            ]),
        ]),
        .init(title: "Daily Reflections", artwork: .dawn, sections: [
            .init(title: "This Week", subtitle: "Short meditations", stories: [
                story("On Being Still", "Psalm 46:10", .river, [
            "\"Be still, and know that I am God.\"",
            "Psalm forty-six does not whisper this from a quiet meadow.",
            "It says it from the middle of an earthquake — mountains falling into the heart of the sea, nations in uproar, kingdoms tottering.",
            "Be still. In Hebrew, the word means let go. Loosen your grip. Stop striving.",
            "It is not a suggestion to relax. It is a command to surrender.",
            "You are not being asked to pretend the storm isn't real.",
            "You are being told who is in the storm with you.",
            "\"God is our refuge and strength, an ever-present help in trouble. Therefore we will not fear.\"",
            "There is a river, the psalm says, whose streams make glad the city of God.",
            "While everything shakes, something quiet still flows.",
            "So just for these next moments, let the hands unclench.",
            "Let the shoulders drop. Let the breath slow.",
            "Be still. And know. He is God, and you are not — and that is the best news of the day.",
        ]),
            ]),
        ]),
        .init(title: "Today in Christ", artwork: .village, sections: [
            .init(title: "Devotion", subtitle: "Walking with Jesus today", stories: [
                story("The Vine and the Branches", "John 15", .meadow, [
            "On the last night before the cross, Jesus gives His friends a picture to hold onto.",
            "\"I am the vine; you are the branches.\"",
            "Not: I am the example and you are the imitators. Something far more intimate — one shared life, flowing from trunk to limb.",
            "\"If you remain in me and I in you, you will bear much fruit.\"",
            "Then the sentence we spend our whole lives learning: \"Apart from me you can do nothing.\"",
            "Not little. Nothing.",
            "A branch has exactly one job, and it is not producing fruit.",
            "Its job is to stay connected. The fruit happens.",
            "Jesus also speaks of pruning — the Father cutting back even healthy branches so they will bear more.",
            "If you are being cut back right now, it may not be punishment. It may be gardening.",
            "\"As the Father has loved me, so have I loved you. Now remain in my love.\"",
            "Remain. Abide. Stay home in that love.",
            "Today, your one job is not to strain for fruit.",
            "It is to stay close to the Vine — and let the life do what life does.",
        ]),
            ]),
        ]),
    ]

    // MARK: Chat topics
    static let chatTopics: [ChatTopic] = [
        .init(title: "Ask me anything", artwork: .river,
              prompts: ["How do I start reading the Bible?",
                        "What does grace really mean?",
                        "Help me pray about a decision."]),
        .init(title: "Mental Health", artwork: .mentalHealth,
              prompts: ["I've been feeling anxious.",
                        "How do I find peace when I'm overwhelmed?",
                        "A verse for a hard day?"]),
        .init(title: "Forgiving Others", artwork: .forgiveness,
              prompts: ["How do I forgive someone who hurt me?",
                        "What does the Bible say about forgiveness?"]),
        .init(title: "Serving Others", artwork: .service,
              prompts: ["How can I serve my community?",
                        "What does it mean to love my neighbor?"]),
        .init(title: "Life Changes", artwork: .lifeChange,
              prompts: ["I'm facing a big change.",
                        "How do I trust God with my future?"]),
        .init(title: "Handling Stress", artwork: .stress,
              prompts: ["Everything feels like too much.",
                        "How do I cast my cares on Him?"]),
    ]

    // MARK: Daily devotional (Daily Bread)
    static let dailyBread = Devotional(
        topic: "Daily Bread",
        minutes: 3,
        artwork: .harvest,
        body: """
In Matthew 6:11, Jesus teaches us to pray, 'Give us today our daily bread.' This simple request carries profound wisdom about how we're meant to live—one day at a time, dependent on God's provision. The Israelites learned this lesson in the wilderness when God provided manna that couldn't be hoarded; it had to be gathered fresh each morning.

How often do we exhaust ourselves trying to secure not just today's needs but tomorrow's and next year's as well? We stockpile resources, relationships, and backup plans, as if God might run out of supply. What anxiety could be released if we truly embraced the daily bread mentality?

This doesn't mean we shouldn't plan wisely, but it does challenge the mindset that everything depends on us. God invites us into the freedom of living present-focused, trusting that what we need for this day will be provided. Tomorrow has its own provision waiting.

Take a moment to consider what daily bread looks like for you right now. Is it physical sustenance? Emotional strength? Wisdom for a decision? Whatever you genuinely need for today, ask for it specifically, then open your eyes to see how God provides.
""",
        prayer: """
Heavenly Father, I approach You from a place of neither spiritual high nor low. In this middle ground, teach me to appreciate the value of consistency in my walk with You. Help me to see that faith isn't just about emotional peaks but about the daily choice to trust and follow. May this quiet steadiness become a foundation upon which deeper connection can grow. Amen.
"""
    )
}
